namespace TimelineNoticeEditor
{
    public static partial class Localization
    {
        private static void AddEditorResources()
        {
            Add(English, "DetailView=Enlarge image|EncodingUnsupported=Only matching UTF-8 or UTF-16 XML encodings are supported.");
            Add(Japanese, "DetailView=画像を拡大して確認|EncodingUnsupported=UTF-8またはUTF-16のXMLに対応しています。文字コードの宣言と実際の形式を合わせてください。");
            Add(Chinese, "DetailView=放大查看图片|EncodingUnsupported=仅支持声明与实际编码一致的UTF-8或UTF-16 XML。");
            Add(Korean, "DetailView=이미지 확대 보기|EncodingUnsupported=선언과 실제 인코딩이 일치하는 UTF-8 또는 UTF-16 XML만 지원합니다.");
            Add(English, "Subtitle=Preview and position SPESPE timeline notices|Settings=Editor|Started=Timeline Notice Editor started.|Stopped=Timeline Notice Editor stopped.|SaveFailed=Could not save settings.|UpdateProblem=Could not safely prepare the update. Check the package, network and installation path.|BrowserFailure=The default browser could not be started.|Folder=Timeline folder|OpenXml=Open XML|ImageFolder=Extra image folder|SaveXml=Back up and save XML|ResetNotice=Reset position|Reload=Reload file|LoadRemote=Load HTTPS image|DesktopPreview=Desktop preview|LockPreview=Lock / click through|Filter=Filter|Scale=Scale|EditorHint=Open a timeline XML, select a notice, and drag its preview. Changes are saved only with the save buttons.|SelectNotice=Select an i-notice.|DragHint=Drag the gold frame; arrow keys move 1, Shift+arrow moves 10. Desktop preview uses WPF coordinates.|ImageScope=i-notice: position and scale are saved in this XML. X=-1 and Y=-1 mean center screen.|Discard=Discard unsaved XML changes?|Loaded=Loaded {0} notices. Select one to preview.|LoadingImage=Loading image…|NoImage=This notice has no image reference.|MissingImage=Image not found: {0}|SavedXml=XML saved with backup: {0}\nReload the timeline in SPESPE to apply it.|OperationFailed=Operation failed: {0}|FileProblem=Check the file, permissions and XML format.|InvalidTimeline=This is not a supported timeline XML.|ExternalChange=The file changed outside this editor. Reload it before saving.|RemoteConsent=Click Load HTTPS image to fetch this URL.|HttpsOnly=Only direct HTTPS image URLs without credentials or redirects are supported.|ImageTooLarge=The image exceeds the preview size limit.|FileTooLarge=The XML exceeds the 32 MB limit.|AmbiguousImage=Multiple images have this filename. Use a unique reference or an explicit image path.");
            Add(Japanese, "Subtitle=SPESPEタイムライン通知の画像プレビュー・位置調整|Settings=編集|Started=Timeline Notice Editorを開始しました。|Stopped=Timeline Notice Editorを停止しました。|SaveFailed=設定を保存できませんでした。|UpdateProblem=更新を安全に準備できませんでした。配置先、通信、Releaseパッケージを確認してください。|BrowserFailure=既定のブラウザを起動できませんでした。|Folder=タイムラインフォルダ|OpenXml=XMLを開く|ImageFolder=追加の画像フォルダ|SaveXml=バックアップしてXML保存|ResetNotice=位置を元に戻す|Reload=再読み込み|LoadRemote=HTTPS画像を取得|DesktopPreview=デスクトップでプレビュー|LockPreview=固定・クリック透過|Filter=絞り込み|Scale=倍率|EditorHint=XMLを開いて通知を選び、プレビューをドラッグして調整します。保存ボタンを押すまでファイルは変更しません。|SelectNotice=i-noticeを選択してください。|DragHint=金枠をドラッグ／矢印キーで1、Shift+矢印で10移動。実画面はWPF座標で表示。|ImageScope=i-notice：位置・倍率をこのXMLに保存します。X=-1・Y=-1の組み合わせは画面中央です。|Discard=保存していないXMLの変更を破棄しますか？|Loaded={0}件の通知を読み込みました。選択してプレビューしてください。|LoadingImage=画像を読み込み中…|NoImage=この通知には画像の指定がありません。|MissingImage=画像が見つかりません：{0}|SavedXml=XMLを保存しました。バックアップ：{0}\n反映にはSPESPEでタイムラインを再読み込みしてください。|OperationFailed=操作に失敗しました：{0}|FileProblem=ファイル、アクセス権、XMLの形式を確認してください。|InvalidTimeline=対応するタイムラインXMLではありません。|ExternalChange=他のソフトがファイルを変更しています。再読み込みしてから保存してください。|RemoteConsent=このURLを読み込むには「HTTPS画像を取得」を押してください。|HttpsOnly=認証情報・転送を含まない直接のHTTPS画像URLに対応しています。|ImageTooLarge=画像がプレビューのサイズ上限を超えています。|FileTooLarge=XMLが32MBの上限を超えています。|AmbiguousImage=同名画像が複数あります。一意の画像名または明示的な画像パスを使用してください。");
            Add(Chinese, "Subtitle=SPESPE时间轴通知图片预览与位置调整|Settings=编辑|Started=Timeline Notice Editor已启动。|Stopped=Timeline Notice Editor已停止。|SaveFailed=无法保存设置。|UpdateProblem=无法安全准备更新，请检查安装路径、网络和Release包。|BrowserFailure=无法启动默认浏览器。|Folder=时间轴文件夹|OpenXml=打开XML|ImageFolder=附加图片文件夹|SaveXml=备份并保存XML|ResetNotice=重置位置|Reload=重新加载|LoadRemote=获取HTTPS图片|DesktopPreview=桌面预览|LockPreview=锁定／鼠标穿透|Filter=筛选|Scale=缩放|EditorHint=打开XML，选择通知并拖动预览。只有点击保存按钮才会修改文件。|SelectNotice=请选择i-notice。|DragHint=拖动金色边框；方向键移动1，Shift+方向键移动10。桌面预览使用WPF坐标。|ImageScope=i-notice：位置和缩放保存在当前XML中。X=-1且Y=-1表示屏幕中央。|Discard=放弃未保存的XML修改？|Loaded=已加载{0}条通知，请选择以预览。|LoadingImage=正在加载图片…|NoImage=此通知未指定图片。|MissingImage=找不到图片：{0}|SavedXml=XML已保存。备份：{0}\n请在SPESPE中重新加载时间轴。|OperationFailed=操作失败：{0}|FileProblem=请检查文件、权限和XML格式。|InvalidTimeline=这不是受支持的时间轴XML。|ExternalChange=文件已被其他软件修改。请重新加载后保存。|RemoteConsent=点击“获取HTTPS图片”来加载此URL。|HttpsOnly=仅支持不含凭据或重定向的直接HTTPS图片URL。|ImageTooLarge=图片超出预览大小限制。|FileTooLarge=XML超出32MB限制。|AmbiguousImage=存在多个同名图片，请使用唯一名称或明确路径。");
            Add(Korean, "Subtitle=SPESPE 타임라인 알림 이미지 미리보기 및 위치 조정|Settings=편집|Started=Timeline Notice Editor를 시작했습니다.|Stopped=Timeline Notice Editor를 중지했습니다.|SaveFailed=설정을 저장하지 못했습니다.|UpdateProblem=업데이트를 안전하게 준비하지 못했습니다. 설치 경로, 네트워크 및 Release 패키지를 확인하세요.|BrowserFailure=기본 브라우저를 시작하지 못했습니다.|Folder=타임라인 폴더|OpenXml=XML 열기|ImageFolder=추가 이미지 폴더|SaveXml=백업 후 XML 저장|ResetNotice=위치 초기화|Reload=다시 읽기|LoadRemote=HTTPS 이미지 가져오기|DesktopPreview=바탕 화면 미리보기|LockPreview=고정 / 클릭 통과|Filter=필터|Scale=배율|EditorHint=XML을 열고 알림을 선택한 다음 미리보기를 드래그하세요. 저장 버튼을 눌러야 파일이 변경됩니다.|SelectNotice=i-notice를 선택하세요.|DragHint=금색 테두리를 드래그하세요. 방향키는 1, Shift+방향키는 10 이동합니다. 바탕 화면은 WPF 좌표를 사용합니다.|ImageScope=i-notice: 위치와 배율을 이 XML에 저장합니다. X=-1 및 Y=-1은 화면 중앙입니다.|Discard=저장하지 않은 XML 변경을 버릴까요?|Loaded=알림 {0}개를 읽었습니다. 미리볼 알림을 선택하세요.|LoadingImage=이미지 읽는 중…|NoImage=이 알림에는 이미지가 없습니다.|MissingImage=이미지를 찾을 수 없습니다: {0}|SavedXml=XML 저장 완료. 백업: {0}\nSPESPE에서 타임라인을 다시 읽으세요.|OperationFailed=작업 실패: {0}|FileProblem=파일, 권한 및 XML 형식을 확인하세요.|InvalidTimeline=지원되는 타임라인 XML이 아닙니다.|ExternalChange=다른 프로그램이 파일을 변경했습니다. 다시 읽은 후 저장하세요.|RemoteConsent=이 URL을 읽으려면 HTTPS 이미지 가져오기를 누르세요.|HttpsOnly=인증 정보나 리디렉션이 없는 직접 HTTPS 이미지 URL만 지원합니다.|ImageTooLarge=이미지가 미리보기 크기 제한을 초과했습니다.|FileTooLarge=XML이 32MB 제한을 초과했습니다.|AmbiguousImage=같은 이름의 이미지가 여러 개입니다. 고유 이름이나 명시적 경로를 사용하세요.");
        }
        private static void Add(string language, string packed) { foreach (var pair in Table(packed)) R[language][pair.Key] = pair.Value.Replace("\\n", "\r\n"); }
    }
}
